# Generated by Django 3.2.5 on 2021-07-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
